typography_spectrum: 0.8598169190809131
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3602785833645612
  lightness: 0.5497232831548899
  saturation: 0.00857000658288598
  rhythmicContrast: 0.57346519571729
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/c54d291f-2a51-412f-bd35-4428134b3c43.jpg
  type: Chair 8 Media
  appId: '832553463485087'
layout_spectrum: 0.695234426530078
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Hart Roberts
  email: hart@chair8media.com
  url: www.chair8media.com
logo: null
name: chair 8 media
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Chair 8 Media
    url: www.chair8media.com
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/68cddbcc-401f-4b03-a94b-e925797c97a4.png
title: chair 8 media
description: Igniting the passions that help shape a brand.
purpose: []
