typography_spectrum: 0.8598169190809131
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3602785833645612
  lightness: 0.5497232831548899
  saturation: 0.00857000658288598
  rhythmicContrast: 0.57346519571729
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.695234426530078
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: chair8media
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Chair 8 Media
    url: www.chair8media.com
    type: external
favicon: null
title: chair 8 media
description: Igniting the passions that help shape a brand.
purpose: []
